# Generated by Django 3.1.4 on 2021-10-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=3000)),
                ('email', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('hostel_name', models.CharField(max_length=30)),
                ('num_room', models.CharField(default=0, max_length=10)),
                ('discount', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('image1', models.FileField(upload_to='media/')),
                ('image2', models.FileField(upload_to='media/')),
                ('image3', models.FileField(upload_to='media/')),
                ('image4', models.FileField(upload_to='media/')),
                ('image5', models.FileField(upload_to='media/')),
                ('image6', models.FileField(upload_to='media/')),
                ('date', models.CharField(max_length=15)),
                ('Restaurant', models.BooleanField(default=False)),
                ('CarBus', models.BooleanField(default=False)),
                ('Stationary', models.BooleanField(default=False)),
                ('BikeRent', models.BooleanField(default=False)),
                ('Wifi', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='bookingrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=30)),
                ('cust_name', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=30)),
                ('payment', models.CharField(max_length=30)),
                ('total', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('confirmation', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
            ],
        ),
    ]
