# Generated by Django 3.2.6 on 2021-10-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211019_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrooms',
            name='room',
        ),
        migrations.AddField(
            model_name='bookingrooms',
            name='branch',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='bookingrooms',
            name='category',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='bookingrooms',
            name='city',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='bookingrooms',
            name='contact',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='bookingrooms',
            name='duration',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='bookingrooms',
            name='email',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='bookingrooms',
            name='gender',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='bookingrooms',
            name='hostel_name',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='bookingrooms',
            name='year',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookingrooms',
            name='college',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookingrooms',
            name='cust_name',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookingrooms',
            name='date',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookingrooms',
            name='payment',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookingrooms',
            name='total',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
