# Generated by Django 3.1.4 on 2021-10-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20211020_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrooms',
            name='payment',
            field=models.BooleanField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='bookingrooms',
            name='reg_payment',
            field=models.BooleanField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookingrooms',
            name='email',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
