# Generated by Django 3.1.4 on 2021-10-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20211021_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='addroom',
            name='room_id',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
