# Generated by Django 3.1.4 on 2021-10-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_addroom_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrooms',
            name='booking_id',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
