# Generated by Django 3.1.4 on 2021-10-21 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_bookingrooms_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrooms',
            name='date',
        ),
        migrations.AddField(
            model_name='bookingrooms',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='addroom',
            name='hostel_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingrooms',
            name='college',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingrooms',
            name='cust_name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingrooms',
            name='hostel_name',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
