# Generated by Django 3.1.4 on 2021-10-21 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20211022_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrooms',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 1, 38, 40, 862120)),
        ),
    ]
