# Generated by Django 3.1.4 on 2021-10-21 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20211022_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrooms',
            name='date',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookingrooms',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 1, 49, 55, 337550)),
        ),
    ]
