# Generated by Django 3.1.4 on 2021-10-26 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20211026_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrooms',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 20, 27, 26, 773690)),
        ),
    ]
