# Generated by Django 3.1.4 on 2021-10-26 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20211026_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroom',
            name='image1',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='bookingrooms',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 22, 17, 22, 594709)),
        ),
    ]
