# Generated by Django 3.1.4 on 2021-10-26 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20211026_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroom',
            name='image1',
            field=models.ImageField(height_field=50, upload_to='media/', width_field=50),
        ),
        migrations.AlterField(
            model_name='bookingrooms',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 22, 54, 18, 235453)),
        ),
    ]
