# Generated by Django 3.1.4 on 2021-10-26 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20211026_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroom',
            name='image1',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='bookingrooms',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 23, 14, 21, 50545)),
        ),
    ]
