# Generated by Django 3.1.4 on 2021-10-27 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20211027_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='addroom',
            name='gender',
            field=models.CharField(default='UniSex', max_length=30),
        ),
        migrations.AlterField(
            model_name='addroom',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookingrooms',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookingrooms',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 23, 31, 28, 574870)),
        ),
    ]
