# Generated by Django 3.1.4 on 2021-10-27 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20211027_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrooms',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 1, 14, 4, 974022)),
        ),
    ]
