# Generated by Django 3.1.4 on 2021-10-28 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20211028_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('hostel_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='bookingrooms',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 21, 28, 44, 180031)),
        ),
    ]
