# Generated by Django 3.1.4 on 2021-10-29 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20211028_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='addroom',
            name='month',
            field=models.CharField(default='1 month', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookingrooms',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 20, 41, 47, 200975)),
        ),
    ]
