# Generated by Django 3.2.6 on 2021-10-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('photo', models.FileField(null=True, upload_to='media/student/')),
                ('aadhar', models.FileField(null=True, upload_to='media/student/')),
                ('contact', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
            ],
        ),
    ]
