# Generated by Django 3.1.4 on 2021-10-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20211020_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
