# Generated by Django 3.1.4 on 2021-10-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20211022_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('hostel_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('Quality', models.CharField(max_length=10)),
                ('Location', models.CharField(max_length=10)),
                ('Space', models.CharField(max_length=10)),
                ('Service', models.CharField(max_length=10)),
                ('Price', models.CharField(max_length=10)),
            ],
        ),
    ]
