# Generated by Django 3.1.4 on 2021-10-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20211027_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=40)),
                ('comment', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
                ('date_comment', models.CharField(max_length=40)),
                ('email_vendor', models.CharField(max_length=100)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
