# Generated by Django 3.1.4 on 2021-10-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='hostel_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
