# Generated by Django 3.1.4 on 2021-10-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_comments_hostel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='gender',
            field=models.CharField(default='UniSex', max_length=10),
        ),
    ]
