# Generated by Django 3.1.4 on 2021-10-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_reviews_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='gender',
            field=models.CharField(default='Boys', max_length=10),
        ),
    ]
