# Generated by Django 3.2.6 on 2021-09-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataform',
            name='count',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dataform',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
