# Generated by Django 3.2.6 on 2021-10-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomate', '0002_auto_20210930_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataform',
            old_name='verified',
            new_name='Verified',
        ),
    ]
