# Generated by Django 3.2.6 on 2021-10-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomate', '0003_rename_verified_dataform_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataform',
            name='count',
        ),
    ]
