# Generated by Django 3.2.6 on 2021-10-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomate', '0007_auto_20211019_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataform',
            name='hostel_photo',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
