# Generated by Django 3.1.4 on 2021-10-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomate', '0009_auto_20211020_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dataform',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dataform',
            name='hostel_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
