# Generated by Django 3.2.8 on 2021-10-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomate', '0010_auto_20211022_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataform',
            old_name='gender',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dataform',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dataform',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dataform',
            name='hcontact',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dataform',
            name='hostel_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dataform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
